### ISSUE TITLE
Parse Error: 

### ISSUE THREAD

**Issue by Lifeischoice** [websharks/ezphp#7]
Just started seeing this error after upgrade to wp 4.7.5 running on php 7.0.19 
[25-May-2017 22:15:14 UTC] PHP Parse error:  syntax error, unexpected '<', expecting end of file in /home/.../public_html/my/wp-content/plugins/ezphp/ezphp.php(82) : eval()'d code on line 23

**Comment by raamdev** [comment]
@Lifeischoice Thanks for the report!

@renzms Can you please attempt to reproduce this when you get a chance?

**Comment by renzms** [comment]
@raamdev 

Unable to replicate this on a clean install using EZPHP, WP 4.7.5 and PHP 7 - 7.1. 

Tested with basic PHP test code as well as some more advanced code samples such as PHP content dripping with s2Member.

@Lifeischoice 

Do you have a sample of the PHP code you have used that caused the issue?

Were you using PHP code straight as is in the Visual Editor or did you add `[php][/php]` shortcode tags in the Visual Editor?

**Comment by Lifeischoice** [comment]
@raamdev @renzms 
Thanks for checking. I have not seen any additional entries in my error log since the 6 entries after upgrading to 4.7.5 . Hopefully that is it but I will report back if it comes back...thanks again. BTW, I use <? php ...?>
